name = "dunamis-store"
compatibility_date = "2026-07-31"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "dunamis-store-db"
database_id = "a7197317-fc8a-41f7-a678-b111d91be50e"

[[r2_buckets]]
binding = "RECEIPTS_BUCKET"
bucket_name = "dunamis-store-receipts"
