INSERT INTO store_settings (
  id,
  store_name,
  store_description,
  logo_url,
  favicon_url,
  primary_color,
  secondary_color,
  contact_email,
  contact_phone,
  whatsapp_number,
  pix_key,
  pix_receiver_name,
  pix_receiver_city,
  order_expiration_minutes,
  allow_pickup,
  allow_delivery,
  pickup_instructions,
  delivery_instructions,
  minimum_order_value,
  store_active
) VALUES (
  1,
  'DUNAMIS STORE',
  'Loja virtual de produtos da igreja.',
  '',
  '',
  '#F5C400',
  '#111111',
  'contato@dunamisstore.local',
  '',
  '',
  '',
  'DUNAMIS STORE',
  'SAO PAULO',
  60,
  1,
  0,
  'Retirada na igreja conforme orientacoes do pedido.',
  'Entrega configuravel pelo painel administrativo.',
  0,
  1
) ON CONFLICT(id) DO NOTHING;
