ALTER TABLE banners ADD COLUMN layout_mode TEXT NOT NULL DEFAULT 'split';
ALTER TABLE banners ADD COLUMN aspect_ratio TEXT NOT NULL DEFAULT '16/7';
ALTER TABLE banners ADD COLUMN image_fit TEXT NOT NULL DEFAULT 'cover';
ALTER TABLE banners ADD COLUMN background_color TEXT NOT NULL DEFAULT '#FFFFFF';
ALTER TABLE banners ADD COLUMN text_color TEXT NOT NULL DEFAULT '#171717';
